_wandb:
    value:
        cli_version: 0.26.0
        e:
            w4y0urjs307fdepuyd9jolr8zisa6vkn:
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 10
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1021821579264"
                        used: "240048201728"
                email: kanaghasivakumar2027@u.northwestern.edu
                executable: C:\NU MSAI Spring 2026\GenAI\Structured-Urban-Synthesis-with-Diffusion-Transformers\dit-env\Scripts\python.exe
                git:
                    commit: bb3800ab872bd4345b3e2c688ffb9220c8cc565f
                    remote: https://github.com/kanaghasivakumar/Structured-Urban-Synthesis-with-Diffusion-Transformers.git
                host: LappyToppy
                memory:
                    total: "16890322944"
                os: Windows-11-10.0.26200-SP0
                program: C:\NU MSAI Spring 2026\GenAI\Structured-Urban-Synthesis-with-Diffusion-Transformers\src\train.py
                python: CPython 3.14.2
                root: C:\NU MSAI Spring 2026\GenAI\Structured-Urban-Synthesis-with-Diffusion-Transformers
                startedAt: "2026-04-20T01:55:36.472295Z"
                writerId: w4y0urjs307fdepuyd9jolr8zisa6vkn
        m: []
        python_version: 3.14.2
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
            "4": 3.14.2
            "5": 0.26.0
            "8":
                - 3
            "12": 0.26.0
            "13": windows-amd64
